In [1]:
import numpy as np
a=np.random.randint(1,100,15)
a

array([28,  6, 31, 28, 72, 50, 62, 94, 88, 16, 84, 79, 78, 78, 66])

In [2]:
b=np.random.randint(1,100,24).reshape(6,4)
b

array([[22, 77, 21, 45],
       [93, 57, 21, 81],
       [46, 53, 43, 87],
       [49, 93, 97, 90],
       [94, 42,  3,  5],
       [73, 54, 83, 30]])

In [3]:
print(np.sort(b))
#Row-Wise Sorting
print("-----------")
print(np.sort(b,axis=0))

[[21 22 45 77]
 [21 57 81 93]
 [43 46 53 87]
 [49 90 93 97]
 [ 3  5 42 94]
 [30 54 73 83]]
-----------
[[22 42  3  5]
 [46 53 21 30]
 [49 54 21 45]
 [73 57 43 81]
 [93 77 83 87]
 [94 93 97 90]]


In [4]:
#Sorted n descending order
print(np.sort(a)[::-1])

[94 88 84 79 78 78 72 66 62 50 31 28 28 16  6]


In [5]:

#Appending to a 1D array (Default axis=None)
arr = np.array([1, 2, 3])
new_arr = np.append(arr, [4, 5, 6])
print(new_arr)


[1 2 3 4 5 6]


In [6]:
#. Appending to a 2D array (axis=None, flattens the array)
arr2d = np.array([[1, 2], [3, 4]])
new_arr2d = np.append(arr2d, [5, 6])
print(new_arr2d)
#Notice that the 2D array was flattened before appending!)

[1 2 3 4 5 6]


In [7]:
#Appending alng axis =0(rows)
arr2d = np.array([[1, 2], [3, 4]])
new_arr2d = np.append(arr2d, [[5, 6]], axis=0)
print(new_arr2d)


[[1 2]
 [3 4]
 [5 6]]


In [8]:
# Appending along axis=1 (columns)
arr2d = np.array([[1, 2], [3, 4]])
new_arr2d = np.append(arr2d, [[5,4,3], [6,15,8]], axis=1)
print(new_arr2d)


[[ 1  2  5  4  3]
 [ 3  4  6 15  8]]


In [9]:
arr2d = np.array([[1, 2], [3, 4]])
new_arr2d = np.append(arr2d, [[5, 6]], axis=0)  
new_arr2d


array([[1, 2],
       [3, 4],
       [5, 6]])

# Key Points to Remember
✅ np.append() does not modify the original array; it returns a new one.<br/>
✅ If axis=None, both arr and values are flattened.<br/>
✅ If an axis is specified, shapes must be compatible.<br/>
✅ It's inefficient for frequent modifications—use np.concatenate() or lists for better performance.<br/>



# np.concatenate((arr1, arr2, ...), axis=0)
Parameters:<br/>
arr1, arr2, ... : tuple of array-like objects<br/>
The arrays to be concatenated. They must have the same shape except for the concatenation axis.<br/>
axis : int, optional (default is 0)<br/>
The axis along which the arrays will be joined.<br/>
axis=0 → Joins along rows (vertically).<br/>
axis=1 → Joins along columns (horizontally).<br/>
axis=None is not allowed (use np.append() if you want to flatten first).<br/>
Returns:<br/>
A new NumPy array that combines the given arrays along the specified axis.

In [10]:
#Concatenating 1 D array

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result = np.concatenate((arr1, arr2))
print(result)


[1 2 3 4 5 6]


In [11]:
#Concatenating 2D array along axis=0(rows)
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])

result = np.concatenate((arr1, arr2), axis=0)
print(result)


[[1 2]
 [3 4]
 [5 6]]


In [12]:
#Concatenating 2D array along axis=1(vertical)
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5,7], [6,8]])

result = np.concatenate((arr1, arr2), axis=1)
print(result)


[[1 2 5 7]
 [3 4 6 8]]


In [13]:
#Conacatenating 3D array along axis=1
arr1 = np.array([[[1, 2],[3,4]], [[5, 6],[7,8]]])
print(arr1)
print(arr1.shape)
print("-------------")
arr2 = np.array([[[5, 6]], [[7, 8]]])
print(arr2)
print(arr2.shape)
print("-----------------")
result = np.concatenate((arr1, arr2), axis=1)
print(result)



[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)
-------------
[[[5 6]]

 [[7 8]]]
(2, 1, 2)
-----------------
[[[1 2]
  [3 4]
  [5 6]]

 [[5 6]
  [7 8]
  [7 8]]]


# np.unique(arr, return_index=False, return_counts=False, return_inverse=False)
arr : array-like<br/>
The input array.<br/>
return_index : bool, optional (default: False)<br/>
*If True, returns the indices of the first occurrence of each unique value.<br/>
return_counts : bool, optional (default: False)<br/>
*If True, returns the count of each unique value.<br/>
return_inverse : bool, optional (default: False)<br/>
*If True, returns an array of indices mapping the original array to the unique values.<br/>
Returns:<br/>
A sorted NumPy array of unique values.<br/>
*(Optional) Indices of the first occurrence of each unique element.<br/>
*(Optional) Counts of each unique element.<br/>
*(Optional) Array mapping original elements to unique elements.<br/>


In [14]:
#1. Finding Unique Elements in a 1D Array


arr = np.array([4, 2, 2, 8, 4, 6, 8, 6])

unique_values = np.unique(arr)
print(unique_values)
arr.value_counts()


[2 4 6 8]


AttributeError: 'numpy.ndarray' object has no attribute 'value_counts'

In [ ]:
#getting unique elements with their counts
unique_values, counts = np.unique(arr, return_counts=True)
print(unique_values)
print(counts)


In [ ]:
# Getting Unique Elements with Their First Occurrence Indices
print(arr)
unique_values, indices = np.unique(arr, return_index=True)
print(unique_values)
print(indices)


In [ ]:
# Getting Unique Elements with Their Inverse Mapping
print(arr)
unique_values, inverse = np.unique(arr, return_inverse=True)
print(unique_values)
print(inverse)
#(The inverse array maps each original value to its position in unique_values.)

In [ ]:
#Using np.unique() on a 2D Array
arr2d = np.array([[1, 2, 3], [3, 2, 1], [1, 1, 3]])
unique_values = np.unique(arr2d)




In [ ]:
print(np.unique(arr,return_index=True,return_counts=True,return_inverse=True))


If all parameters (return_index=True, return_counts=True, return_inverse=True) are set to True in<br/> np.unique(), the function will return four arrays in the following sequence:
1️⃣ Unique Values (Sorted Unique Elements) <br/>2️⃣ Indices (First Occurrence Indices in Original Array)<br/> 3️⃣ Inverse Mapping (Mapping Original Elements to Unique Values)<br/> 4️⃣ Counts (Frequency of Each Unique Value)

# Syntax:np.expand_dims(arr, axis)
arr: Input array<br/>
axis: The position where the new axis should be added (0 for row-wise, 1 for column-wise, etc.)


In [ ]:
#1️⃣ Basic Example: Adding a New Axis

arr = np.array([1, 2, 3])
expanded_arr = np.expand_dims(arr, axis=0)  # Add new axis at position 0

print("Original Shape:", arr.shape)        # (3,)
print("Expanded Shape:", expanded_arr.shape)  # (1, 3)
#📌 Effect: Converts a 1D array [1, 2, 3] into a row vector [[1, 2, 3]] (2D).

In [ ]:
expanded_col = np.expand_dims(arr, axis=1)  # Add new axis at position 1

print("Expanded Shape (Column Vector):", expanded_col.shape)  # (3, 1)
expanded_col
# Effect: Converts [1, 2, 3] into a column vector:

In [ ]:
# Using np.expand_dims() on a 2D Array
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2d)
print("------------")
expanded_arr2d = np.expand_dims(arr2d, axis=0)  # Add axis at 0
print("Original aray shape",arr2d.shape)
print(expanded_arr2d)
print("Expanded array shape: ",expanded_arr2d.shape)  # (1, 2, 3)


np.where()<br/>
# np.where(condition, [x, y])
*If only condition is provided, it returns indices where the condition is True.<br/>
*If x and y are also provided, it replaces values based on the condition:<br/>
*Returns elements from x where condition is True<br/>
*Returns elements from y where condition is False<br/>


In [ ]:
#1️⃣ Find Indices Where Condition is True
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print(np.where(arr>35))
indices = np.where(arr > 25)  # Find indices where values > 25

print("Indices:", indices)  # Output: (array([2, 3, 4]),)
print("Values:", arr[indices])  # Output: [30 40 50]


In [ ]:
#2️⃣ Replace Values Based on Condition
arr2 = np.array([10, 20, 30, 40, 50])
new_arr = np.where(arr2 > 25, 1, 0)  # If >25, replace with 1, else 0

print(new_arr)  # Output: [0 0 1 1 1]


In [ ]:
# 3️⃣ Using np.where() in a 2D Array
arr2d = np.array([[10, 20, 30], [40, 50, 60]])
indices = np.where(arr2d > 25)

print("Row Indices:", indices[0])  # Output: [0 1 1 1]
print("Col Indices:", indices[1])  # Output: [2 0 1 2]
print("Values:", arr2d[indices])  # Output: [30 40 50 60]


In [16]:
a=np.arange(1,10)
a
print(np.where(a%2==0))

(array([1, 3, 5, 7], dtype=int64),)


syntax: 
# np.argmax() and np.argmin()
Returns the index of the maximum and minimum value in the array.\
Works on 1D and multi-dimensional arrays (with an optional axis parameter).

In [18]:
import numpy as np
#Example (1D array)
arr = np.array([3, 7, 2, 9, 5])
max_index = np.argmax(arr)
min_index=np.argmin(arr)
print(max_index)  # Output: 3 (index of 9)
print(min_index)

3
2


# Using axis for Multi-Dimensional Arrays
When applied to a 2D array, you can specify the axis:\

axis=0: Finds the index along columns (vertical).\
axis=1: Finds the index along rows (horizontal).

In [21]:
arr2d = np.array([[10, 20, 5], 
                  [40, 15, 25],[6,62,93]])

print(np.argmax(arr2d, axis=0))  # Max indices along columns → [1, 2, 2]
print(np.argmax(arr2d, axis=1))  # Max indices along rows → [1, 0 2]

print(np.argmin(arr2d, axis=0))  # Min indices along columns → [2, 1, 0]
print(np.argmin(arr2d, axis=1))  # Min indices along rows → [2, 1,0]

#Handling Ties
#If multiple values are the maximum/minimum, the function returns the first occurrence.

arr = np.array([1, 3, 7, 7, 2])
print(np.argmax(arr))  # Output: 2 (first occurrence of 7)

















[1 2 2]
[1 0 2]
[2 1 0]
[2 1 0]
2


Syntax:
# np.cumsum() – Cumulative Sum
Computes the cumulative sum of an array along a given axis.\
Each element in the output array is the sum of all previous elements up to that position.\


In [24]:
#Example (1D array)
import numpy as np

arr = np.array([1, 2, 3, 4])
cumulative_sum = np.cumsum(arr)

print(cumulative_sum)  
# Output: [1 3 6 10]  (1, 1+2, 1+2+3, 1+2+3+4)
#Example (2D array)
arr2d = np.array([[1, 2, 3], 
                  [4, 5, 6]])

print("Cumulative sum along the coloumns:",np.cumsum(arr2d, axis=0))  # Column-wise sum
# Output:
# [[ 1  2  3]
#  [ 5  7  9]]

print("cumulative sum along the row: ",np.cumsum(arr2d, axis=1))  # Row-wise sum
# Output:
# [[ 1  3  6]
#  [ 4  9 15]]


[ 1  3  6 10]
Cumulative sum along the coloumns: [[1 2 3]
 [5 7 9]]
cumulative sum along the row:  [[ 1  3  6]
 [ 4  9 15]]


Syntax:
# np.cumprod() – Cumulative Product
Computes the cumulative product of an array.\
Each element is the product of all previous elements up to that position.

In [26]:
# 1D Array 
arr = np.array([1, 2, 3, 4])
cumulative_product = np.cumprod(arr)

print(cumulative_product)
# Output: [1 2 6 24]  (1, 1×2, 1×2×3, 1×2×3×4)


[ 1  2  6 24]


In [27]:
# 2 D Array 
arr2d = np.array([[1, 2, 3], 
                  [4, 5, 6]])

print(np.cumprod(arr2d, axis=0))  # Column-wise product
# Output:
# [[ 1  2  3]
#  [ 4 10 18]]

print(np.cumprod(arr2d, axis=1))  # Row-wise product
# Output:
# [[  1   2   6]
#  [  4  20 120]]


[[ 1  2  3]
 [ 4 10 18]]
[[  1   2   6]
 [  4  20 120]]


3. Practical Applications
np.cumsum():

Prefix Sum (useful in range sum queries).
Running totals in finance and statistics.
np.cumprod():

Compounding growth calculations (e.g., investments).\
Factorial computations (e.g., np.cumprod(np.arange(1, n+1)) for n!).

Syntax:
# np.percentile(arr, q, axis=None, interpolation='linear', keepdims=False)
arr → Input array.\
q → Percentile(s) to compute (0-100).\
axis (optional) → Axis along which to compute the percentile.\
axis=None (default) → Flattens the array.\
axis=0 → Computes percentile column-wise.\
axis=1 → Computes percentile row-wise.\
interpolation (deprecated, replaced by method in newer versions) → Determines how to handle non-integer ranks.\
keepdims (optional) → If True, retains reduced dimensions.\

In [29]:
import numpy as np
#single percentile
arr = np.array([1, 3, 5, 7, 9])
p_50 = np.percentile(arr, 50)  # 50th percentile (median)

print(p_50)  # Output: 5
#Multiple Percentiles
percentiles = np.percentile(arr, [25, 50, 75])  # 25th, 50th, 75th percentiles
print(percentiles)  # Output: [3. 5. 7.]


5.0
[3. 5. 7.]


25th percentile (Q1): 3\
50th percentile (Median, Q2): 5\
75th percentile (Q3): 7

In [30]:
#2 D Array
arr2d = np.array([[10, 20, 30], 
                  [40, 50, 60]])

print(np.percentile(arr2d, 50, axis=0))  # Column-wise percentiles
# Output: [25. 35. 45.]

print(np.percentile(arr2d, 50, axis=1))  # Row-wise percentiles
# Output: [20. 50.]


[25. 35. 45.]
[20. 50.]


# Handling Edge Cases
If q=0, returns minimum.\
If q=100, returns maximum.\
If q falls between two values, linear interpolation is used by default.
# Practical Applications
 Practical Applications\
Data analysis (finding quartiles, medians).\
Outlier detection (e.g., using the IQR method).\
Setting thresholds (e.g., top 10% of values in a dataset).\

#Syntax: 
# np.histogram(arr, bins=10, range=None, density=False)
Parameters:
arr → Input array.\
bins → Number of bins or a list of bin edges.\
range (optional) → Tuple specifying the minimum and maximum range ((min, max)).\
density → If True, returns the probability density function (normalizing the count).


In [31]:
# Basic Histogram
import numpy as np

data = np.array([1, 2, 1, 2, 3, 3, 3, 4, 4, 5])

hist, bin_edges = np.histogram(data, bins=5)

print("Histogram counts:", hist)  
print("Bin edges:", bin_edges)


Histogram counts: [2 2 3 2 1]
Bin edges: [1.  1.8 2.6 3.4 4.2 5. ]


In [32]:
# Custom Bins
hist, bin_edges = np.histogram(data, bins=[0, 2, 4, 6])  # Custom bin edges
print(hist)  
print(bin_edges)


[2 5 3]
[0 2 4 6]


In [33]:
# Normalized Histogram
hist, bin_edges = np.histogram(data, bins=5, density=True)
print(hist)  


[0.25  0.25  0.375 0.25  0.125]


# np.corrcoef(x, y=None, rowvar=True)
Parameters:
x → A 1D or 2D array.\
y (optional) → A second dataset (if omitted, x is compared with itself).\
rowvar=True → If True, rows are variables & columns are observations.\
Set rowvar=False if each row represents an observation and each column is a variable\

In [35]:
# correlation between Two Arrays 
import numpy as np

x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 6, 8, 10])

correlation_matrix = np.corrcoef(x, y)
print(correlation_matrix)


[[1. 1.]
 [1. 1.]]


In [36]:
# correlation coefficient in 2 D array 
data = np.array([[1, 2, 3], 
                 [2, 4, 6], 
                 [3, 6, 9]])

correlation_matrix = np.corrcoef(data)
print(correlation_matrix)


# Syntax: 
# np.isin(element, test_elements)
element: The array whose elements we want to check.
test_elements: The values we want to check for existence.
import numpy as np


In [40]:

arr = np.array([1, 2, 3, 4, 5])
test_values = [2, 4, 6]
print(np.isin(arr, test_values))
print(result)
arr[np.isin(arr,test_values)]

[False  True False  True False]
[False  True False  True False]


array([2, 4])

In [44]:
w=np.array([12,15,16,78.54])
print(w)
type(w)

[12.   15.   16.   78.54]


numpy.ndarray