In [1]:
# How to create Numpy Array
import numpy as np
# Ye library pehle import karni padegi numpy array ko banane ke liye 
a=np.array([1,2,3,4,5])# we can call 1D Numpy array vector

print(type(a))
print(a)


<class 'numpy.ndarray'>
[1 2 3 4 5]


In [2]:
# 2D and 3D
b=np.array([[1,2,3],[4,5,6],[7,8,9]])# we can call 2D Numpy array as matrix
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
# 3D Numpy array banane ke liye 3D we can send ,similarly can make higher dimension Numpy array We call them Tensors



In [4]:
#dtype
# by default if we dont specifically provide the dtype then it is integer , and we can change data type
np.array([1,2,3],dtype=float)


array([1., 2., 3.])

In [5]:
np.array([1,2,3],dtype=bool)
#Any non zero number ko python True treat Karta hai
print(np.array([1+2j,3j,45],dtype=complex))

[ 1.+2.j  0.+3.j 45.+0.j]


In [6]:
#np.arange()
np.arange(1,11)
# The second Parameter is excluded and the first parameter is included i.e,. 11 is excluded and 1 is include 
# it will give the numbers from  to 10 integers 
np.arange(1,11,2)
#Third Parameter is of Jump it will skip 1 minus p that much integers that is mentioned in third paarameter , here it is skipping 1 number

array([1, 3, 5, 7, 9])

In [7]:
#reshape()
np.arange(1,13).reshape(3,4)

# Basically we can reshape the array of one shape to other shape ,but just one thing is to make sure the we get the same number
#of elements after reshaping as the number of elements in original array 
# We can reshape it either in (4,3) (2,6),(6,2) etc

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
#np.ones(), np.zeros()
np.ones((3,4))
# Inka use matrix ko initialize karne me hota hai , Deep learning me jab ham convolution neura networks padhte hain 
# wahan har layer ki node agli layer ke saare nodes se connect rehti hai toh whan har ek arrow ke corresponding ek weight hota hai
#toh weight ko initialize karne me bhi use karte hain ham in functions ko
np.zeros((4,3))
np.random.random((3,4))# Initializing with the Random numbers 

array([[0.03633931, 0.47497276, 0.36660151, 0.86297476],
       [0.49064787, 0.07895215, 0.84702762, 0.30126947],
       [0.94963409, 0.33687219, 0.02387957, 0.18465475]])

In [9]:
#np.linspace
np.linspace(-10,10,10)

# Ye function kisi given range me equal distant pe numbers generate karke deta hai, is example me yahan pe 10 numbers
#generate karke de raha kyunki Third parameter wahi batata ki kitne numbers generate karke dene hain , aur pehle two parameters 
#eange ko define karte hain 
# Basically between any two points distant will be equal 
# By default it gives float value but we can change dtype also 
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [10]:
#np.identity
# Ye Identity Matrix banane ke liye hai
np.identity(3)
#Parameter Jo paass kiya hai wo baatega kitni Dimension ki Identity Matrix banani hai 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Array Attributes


In [11]:
#Array Attributes
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [12]:
#ndim 
a3.ndim
# Ye ksis bhi Array ki dimension ko batega ki wo kitni Dimension ka hai 

3

In [13]:
# shape
a3.shape
# Ye batega ki har dimension me Element kitne hain 
print(a3)
# Isko interpret kaise karenge let say a3 ke liye dekhte hain , Kyunki 3 Dimension hain pehle number bata raha hain 
#ki kitne 2 dimension ke array hain or last ke 2 numbers bataenge ki 2D Array ki shape kya hai matlab row kitni hain or coloumn
#kitni hain 

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [14]:
#Size 
print(a2.size)
# Ye batega ki array mein elements kitne hain


12


In [15]:
#item size
print(a3.itemsize)
print(a2.itemsize)
print(a1.itemsize)
# Ye bataega ki har item(Element) Array ka  memory me kitne byte le raha hai 

4
8
4


In [16]:
#dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)
# ye batega Array ke elements ka dtype kya hai

int32
float64
int32


# Changing Data Type
Agar ham Chahein to pehle se bane Array ka bhi dtype change karsakte hain
use kyun karne ki zarurat padti hain , so maanlo hamein logon ki age store karni hai array me toh hame pehle hi pata hai ki bahot bade number hamare nahi aaenge lekin abhi hamne dekha bydefault array numbers ko int 64 me store karta hai jo zyada memory leta hai toh agar ham int 32 me change kardein data type toh memory obviously bachegi 


In [17]:
print(a3.dtype)
a3.astype(float)
print(a3.dtype)

int32
int32


# Array Operations

In [18]:
a1= np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)
print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [19]:
#scalar Operation

#Arithmetic Operation
print(a1*2)
#All the elements are ,multiplied by 2
print(a1**2)

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


In [20]:
#Relational Operator
print(a1==15)
# Every element of the array will be checked by 15 if any element is equal to the 15 then for that True 
# Otherwise False will be returned 
print(a1>15)
print(a1<15)
# basically ,condition will bechecked for every numbers for those he condition hold true true will returened ,
#Otherwise false will be returned

[[False False False False]
 [False False False False]
 [False False False False]]
[[False False False False]
 [False False False False]
 [False False False False]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [21]:
#vector Operations
#Arithmetic 
print(a1+a2)
#Since Shape of both array is same item adds element wise


[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]


# Array function


In [22]:
a1 = np.random.random((4,4))
a1=np.round(a1*100)
print(a1)

[[45. 83. 27. 46.]
 [41. 87. 64. 65.]
 [57. 77. 29. 93.]
 [93. 13. 35. 55.]]


In [23]:
#max/min/Sum/Prod
print(np.max(a1))
print(np.min(a1))
print(np.sum(a1))
print(np.prod(a1))
# 0->Coloumn 1->Row
print(np.max(a1,axis=0))
# It gives maximum element in each coloumn 
print(np.max(a1,axis=1))
#It gives maximum element in each row



93.0
13.0
910.0
1.8963225259699749e+27
[93. 87. 64. 93.]
[83. 87. 93. 93.]


In [24]:
#mean/median/std/var
print(np.mean(a1))
print(np.mean(a1,axis=1))
#mean Row wise
print(np.mean(a1,axis=0))
#Coloumn wise mean
#median kya deta hai , list ko sort karne ke bad beech wala (middle element) ko deta hai 
print(np.median(a1,axis=1))
print(np.std(a1,axis=1))
print(np.var(a1,axis=1))

56.875
[50.25 64.25 64.   49.  ]
[59.   65.   38.75 64.75]
[45.5 64.5 67.  45. ]
[20.36387733 16.2692194  23.89560629 29.42787794]
[414.6875 264.6875 571.     866.    ]


In [25]:
#trignometric functions
print(np.sin(a1))

[[ 0.85090352  0.96836446  0.95637593  0.90178835]
 [-0.15862267 -0.82181784  0.92002604  0.82682868]
 [ 0.43616476  0.99952016 -0.66363388 -0.94828214]
 [-0.94828214  0.42016704 -0.42818267 -0.99975517]]


In [26]:
#Dot Product
a2=np.arange(12).reshape(3,4)
a3=np.arange(12,24).reshape(4,3)
a3
print(np.dot(a2,a3))

[[114 120 126]
 [378 400 422]
 [642 680 718]]


In [27]:
#log and exponents 
print(np.log(a1))
print(np.exp(a1))

[[3.80666249 4.41884061 3.29583687 3.8286414 ]
 [3.71357207 4.46590812 4.15888308 4.17438727]
 [4.04305127 4.34380542 3.36729583 4.53259949]
 [4.53259949 2.56494936 3.55534806 4.00733319]]
[[3.49342711e+19 1.11286375e+36 5.32048241e+11 9.49611942e+19]
 [6.39843494e+17 6.07603023e+37 6.23514908e+27 1.69488924e+28]
 [5.68572000e+24 2.75851345e+33 3.93133430e+12 2.45124554e+40]
 [2.45124554e+40 4.42413392e+05 1.58601345e+15 7.69478527e+23]]


In [28]:
#round/floor/ceil
print(np.round(a1))
print(np.ceil(a1))
print(np.floor(a1))

[[45. 83. 27. 46.]
 [41. 87. 64. 65.]
 [57. 77. 29. 93.]
 [93. 13. 35. 55.]]
[[45. 83. 27. 46.]
 [41. 87. 64. 65.]
 [57. 77. 29. 93.]
 [93. 13. 35. 55.]]
[[45. 83. 27. 46.]
 [41. 87. 64. 65.]
 [57. 77. 29. 93.]
 [93. 13. 35. 55.]]


In [29]:
print(np.random.random((2,3))*100)
print(np.round(np.random.random((2,3))*100))

[[77.78096487 85.68204351 73.52627807]
 [39.38089895 52.09821527 99.14366761]]
[[65. 70. 82.]
 [24. 31. 60.]]


In [30]:
#Indexing and Slicing
a1=np.arange(10)#1D Array
a2=np.arange(12).reshape(3,4)#2D array
a3=np.arange(8).reshape(2,2,2)#3D array
print(a1)
print(a2)
print(a3)
#Indexing
print(a1[-1])
print(a2[2,3])
print(a3[1,0,1])
print(a3[1,0])

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
9
11
5
[4 5]


In [31]:
#Slicing 
print(a1)

[0 1 2 3 4 5 6 7 8 9]


In [32]:
# Print Numbers from 2 to 4 
print(a[2:5])
print(a[2:5:2])
print(a[5:0:-2])

[3 4 5]
[3 5]
[5 3]


In [33]:
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [34]:
print(a2[0,:])

[0 1 2 3]


In [35]:
print(a2[:,2])
# 5 6
# 9 10 
print(a2[1:,1:3])
# 0 3
# 8 11
print(a2[::2,::3])
# 0 3
# 4 7
# 8 11
print(a2[:,::3])
# 0  1  2  3
# 8  9 10 11
print(a2[::2,:])
# 1 9 
# 3 11
print(a2[::2,1::2])

[ 2  6 10]
[[ 5  6]
 [ 9 10]]
[[ 0  3]
 [ 8 11]]
[[ 0  3]
 [ 4  7]
 [ 8 11]]
[[ 0  1  2  3]
 [ 8  9 10 11]]
[[ 1  3]
 [ 9 11]]


In [36]:
a3 = np.arange(27).reshape(3,3,3)
print(a3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [37]:
print(a3[1])


[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [38]:
print(a3[::2])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [39]:
print(a3[0,1,:])

[3 4 5]


In [40]:
print(a3[1,:,1])

[10 13 16]


In [41]:
print(a3[2,1:,1:])

[[22 23]
 [25 26]]


In [42]:
print(a3[::2,0,::2])

[[ 0  2]
 [18 20]]


In [43]:
#Iterating 
print(a1)#1D 
print("-----")
print(a2)#2D
print("------")
print(a3)#3D 
print("-------")
for i in a2:
    print(i)
    print(type(i))
    print(i.shape)
print("-------")
for i in a2:
    for j in i:
        print(j,end=" ")
    print()
print("------")
for i in  a2:
    print(i[1::])
    
    
    
    
    
    
for i in a3:
    print(i)

[0 1 2 3 4 5 6 7 8 9]
-----
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
------
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
-------
[0 1 2 3]
<class 'numpy.ndarray'>
(4,)
[4 5 6 7]
<class 'numpy.ndarray'>
(4,)
[ 8  9 10 11]
<class 'numpy.ndarray'>
(4,)
-------
0 1 2 3 
4 5 6 7 
8 9 10 11 
------
[1 2 3]
[5 6 7]
[ 9 10 11]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [44]:
#Transpose 
print(np.transpose(a2))
a2=np.transpose(a2)
print(np.shape(a2))
a2=a2.T
print(a2.shape)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
(4, 3)
(3, 4)


In [45]:
#ravel() 
#this Convert any dimension array into 1 D array 
print(a2)
print("-----------")
print(a2.ravel())
print("-------------")
print(a3.ravel())

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-----------
[ 0  1  2  3  4  5  6  7  8  9 10 11]
-------------
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [51]:
#Stacking 

#Stacking wwe can only dp when shape is same 
#Horizantal stacking
x1 = np.arange(12).reshape(3,4)
x2 = np.arange(12,24).reshape(3,4)
x3=np.hstack((x1,x2))# horizantal stacking
x4=np.vstack((x1,x2))
# we can stack as many arrays  as we want 
print(x3)

print(x3.shape)
print(x4)
print(x4.shape)

[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]
(3, 8)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
(6, 4)


In [58]:
#Splitting
print(np.hsplit(x3,2))
print("----------")
print(np.hsplit(x3,4))
print("-------------")
print(np.vsplit(x4,2))

[array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])]
----------
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]]), array([[12, 13],
       [16, 17],
       [20, 21]]), array([[14, 15],
       [18, 19],
       [22, 23]])]
-------------
[array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])]
